"""Standalone speech-to-text — transcribe audio without the chat pipeline.

Sends WAV files to the /v1/speech-to-text endpoint and prints the recognized text.
Demonstrates language override and error handling for oversized input.
"""

import sys
from pathlib import Path

from ova_sdk import OVA, OVARequestError

_EXAMPLES_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = _EXAMPLES_DIR.parent / "output" / "transcribe-audio"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# Path to a WAV file to transcribe (generated by quickstart example)
AUDIO_FILE = _EXAMPLES_DIR.parent / "output" / "quickstart" / "quickstart.wav"

if not AUDIO_FILE.exists():
    print(f"Audio file not found: {AUDIO_FILE}")
    print("Run 01-quickstart.py first to generate it.")
    sys.exit(1)

client = OVA()
txt_path = OUTPUT_DIR / "transcription.txt"

print("Waiting for server...")
client.wait_until_ready()

with open(txt_path, "w") as f:
    # -- Basic transcription --
    print(f"\n=== Transcribing: {AUDIO_FILE} ===")
    result = client.transcribe(AUDIO_FILE)
    print(f"  Text: {result.text!r}")
    f.write(f"=== {AUDIO_FILE} ===\n{result.text}\n\n")

    # -- Transcribe from bytes --
    print("\n=== Transcribing from bytes ===")
    wav_bytes = AUDIO_FILE.read_bytes()
    result = client.transcribe(wav_bytes)
    print(f"  Text: {result.text!r}")
    f.write(f"=== From bytes ===\n{result.text}\n\n")

    # -- Language override --
    print("\n=== Transcribing with language override (Spanish) ===")
    result = client.transcribe(AUDIO_FILE, language="es")
    print(f"  Text: {result.text!r}")
    f.write(f"=== Language override (Spanish) ===\n{result.text}\n")

print(f"  Saved transcriptions to {txt_path}")

# -- Error handling: oversized audio --
print("\n=== Error handling: oversized audio ===")
try:
    # Server default limit is 20MB; this simulates exceeding it
    fake_large = b"RIFF" + b"\x00" * (25 * 1024 * 1024)
    client.transcribe(fake_large)
except OVARequestError as e:
    print(f"  Caught OVARequestError (status {e.status_code}): {e}")

print("\nDone!")
